# Generated by Django 4.2.7 on 2025-11-25 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='videos/originals/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/')),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_progress', models.IntegerField(default=0, help_text='Processing percentage')),
                ('error_message', models.TextField(blank=True)),
                ('hls_playlist', models.CharField(blank=True, help_text='Path to master.m3u8', max_length=500)),
                ('views', models.IntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('bitrate', models.IntegerField(help_text='Bitrate in kbps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='videos.video')),
            ],
            options={
                'ordering': ['quality'],
                'unique_together': {('video', 'quality')},
            },
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.IntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('duration', models.FloatField(help_text='Segment duration in seconds')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.videoquality')),
            ],
            options={
                'ordering': ['segment_number'],
                'unique_together': {('quality', 'segment_number')},
            },
        ),
    ]
