# Generated by Django 4.2.7 on 2025-11-25 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='video',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='fps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='hls_playlist',
            field=models.CharField(blank=True, help_text='Path to master.m3u8', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/originals/'),
        ),
        migrations.AddField(
            model_name='video',
            name='processing_progress',
            field=models.IntegerField(default=0, help_text='Processing percentage'),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
        migrations.CreateModel(
            name='VideoQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('360p', '360p'), ('480p', '480p'), ('720p', '720p'), ('1080p', '1080p')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('bitrate', models.IntegerField(help_text='Bitrate in kbps')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualities', to='videos.video')),
            ],
            options={
                'ordering': ['quality'],
                'unique_together': {('video', 'quality')},
            },
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_number', models.IntegerField()),
                ('file_path', models.CharField(max_length=500)),
                ('duration', models.FloatField(help_text='Segment duration in seconds')),
                ('quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.videoquality')),
            ],
            options={
                'ordering': ['segment_number'],
                'unique_together': {('quality', 'segment_number')},
            },
        ),
    ]
